<a href="https://colab.research.google.com/github/JasonWachira/SemProject_MLEngine/blob/main/Logistics_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# a) How many rows, columns does the dataset have
import numpy as np
import pandas as pd


df = pd.read_csv("Logistics.csv")
df.shape

(21201, 29)

In [7]:
# b) Data types contained in the dataset
df.dtypes

Order No                                      object
User Id                                       object
Vehicle Type                                  object
Platform Type                                  int64
Personal or Business                          object
Placement - Day of Month                       int64
Placement - Weekday (Mo = 1)                   int64
Placement - Time                              object
Confirmation - Day of Month                    int64
Confirmation - Weekday (Mo = 1)                int64
Confirmation - Time                           object
Arrival at Pickup - Day of Month               int64
Arrival at Pickup - Weekday (Mo = 1)           int64
Arrival at Pickup - Time                      object
Pickup - Day of Month                          int64
Pickup - Weekday (Mo = 1)                      int64
Pickup - Time                                 object
Arrival at Destination - Day of Month          int64
Arrival at Destination - Weekday (Mo = 1)      int64
Arrival at Destination - Time                 object
Distance (KM)                                  int64
Temperature                                  float64
Precipitation in millimeters                 float64
Pickup Lat                                   float64
Pickup Long                                  float64
Destination Lat                              float64
Destination Long                             float64
Rider Id                                      object
Time from Pickup to Arrival                    int64
dtype: object

In [9]:
# c) Is the dataset complete
df.isnull().sum()

Order No                                         0
User Id                                          0
Vehicle Type                                     0
Platform Type                                    0
Personal or Business                             0
Placement - Day of Month                         0
Placement - Weekday (Mo = 1)                     0
Placement - Time                                 0
Confirmation - Day of Month                      0
Confirmation - Weekday (Mo = 1)                  0
Confirmation - Time                              0
Arrival at Pickup - Day of Month                 0
Arrival at Pickup - Weekday (Mo = 1)             0
Arrival at Pickup - Time                         0
Pickup - Day of Month                            0
Pickup - Weekday (Mo = 1)                        0
Pickup - Time                                    0
Arrival at Destination - Day of Month            0
Arrival at Destination - Weekday (Mo = 1)        0
Arrival at Destination - Time                    0
Distance (KM)                                    0
Temperature                                   4366
Precipitation in millimeters                 20649
Pickup Lat                                       0
Pickup Long                                      0
Destination Lat                                  0
Destination Long                                 0
Rider Id                                         0
Time from Pickup to Arrival                      0
dtype: int64

In [10]:
# d) Slice first 15 and last 20 and merge them into a new data frame
new_df = pd.concat([df.head(15), df.tail(20)])
new_df

,Order No,User Id,Vehicle Type,Platform Type,Personal or Business,Placement - Day of Month,Placement - Weekday (Mo = 1),Placement - Time,Confirmation - Day of Month,Confirmation - Weekday (Mo = 1),...,Arrival at Destination - Time,Distance (KM),Temperature,Precipitation in millimeters,Pickup Lat,Pickup Long,Destination Lat,Destination Long,Rider Id,Time from Pickup to Arrival
0,Order_No_4211,User_Id_633,Bike,3,Business,9,5,9:35:46 am,9,5,...,10:39:55 am,4,20.4,NaN,-1.317755,36.830370,-1.300406,36.829741,Rider_Id_432,745
1,Order_No_25375,User_Id_2285,Bike,3,Personal,12,5,11:16:16 am,12,5,...,12:17:22 pm,16,26.4,NaN,-1.351453,36.899315,-1.295004,36.814358,Rider_Id_856,1993
2,Order_No_1899,User_Id_265,Bike,3,Business,30,2,12:39:25 pm,30,2,...,1:00:38 pm,3,NaN,NaN,-1.308284,36.843419,-1.300921,36.828195,Rider_Id_155,455
3,Order_No_9336,User_Id_1402,Bike,3,Business,15,5,9:25:34 am,15,5,...,10:05:27 am,9,19.2,NaN,-1.281301,36.832396,-1.257147,36.795063,Rider_Id_855,1341
4,Order_No_27883,User_Id_1737,Bike,1,Personal,13,1,9:55:18 am,13,1,...,10:25:37 am,9,15.4,NaN,-1.266597,36.792118,-1.295041,36.809817,Rider_Id_770,1214
5,Order_No_7408,User_Id_1342,Bike,3,Business,14,5,3:07:35 pm,14,5,...,4:23:41 pm,9,27.2,NaN,-1.302583,36.767081,-1.257309,36.806008,Rider_Id_124,3191
6,Order_No_22680,User_Id_2803,Bike,3,Business,9,5,9:33:45 am,9,5,...,10:19:45 am,5,20.3,NaN,-1.279395,36.825364,-1.276574,36.851365,Rider_Id_114,1380
7,Order_No_21578,User_Id_1075,Bike,3,Business,11,1,2:13:01 pm,11,1,...,2:33:26 pm,3,28.7,NaN,-1.252796,36.800313,-1.255189,36.782203,Rider_Id_913,646
8,Order_No_5234,User_Id_733,Bike,3,Business,30,2,11:10:44 am,30,2,...,1:19:35 pm,9,NaN,NaN,-1.255189,36.782203,-1.300255,36.825657,Rider_Id_394,3398
9,Order_No_1768,User_Id_2112,Bike,3,Business,23,5,4:48:54 pm,23,5,...,6:31:57 pm,14,24.6,NaN,-1.225322,36.808550,-1.215601,36.891686,Rider_Id_660,3439
10,Order_No_823,User_Id_2820,Bike,3,Personal,15,3,9:23:37 am,15,3,...,10:32:29 am,9,16.4,NaN,-1.329118,36.789237,-1.290342,36.788528,Rider_Id_208,1056
11,Order_No_2533,User_Id_704,Bike,1,Business,2,2,3:43:20 pm,2,2,...,5:22:25 pm,17,26.1,NaN,-1.258414,36.804800,-1.286018,36.897534,Rider_Id_937,3898
12,Order_No_7842,User_Id_1990,Bike,3,Business,23,4,2:37:42 pm,23,4,...,3:45:59 pm,10,24.6,NaN,-1.255872,36.722296,-1.275442,36.766021,Rider_Id_868,2642
13,Order_No_6452,User_Id_3295,Bike,3,Business,25,5,9:12:08 am,25,5,...,10:15:58 am,21,20.9,NaN,-1.257147,36.795063,-1.390867,36.767424,Rider_Id_536,2904
14,Order_No_9463,User_Id_248,Bike,3,Business,23,4,10:05:04 am,23,4,...,10:33:52 am,1,NaN,NaN,-1.304735,36.784605,-1.299323,36.775337,Rider_Id_607,407
21181,Order_No_7229,User_Id_3194,Bike,3,Business,26,3,10:16:03 am,26,3,...,10:53:23 am,8,23.9,NaN,-1.255189,36.782203,-1.285417,36.795115,Rider_Id_116,666
21182,Order_No_11816,User_Id_590,Bike,3,Business,22,5,10:42:08 am,22,5,...,12:09:43 pm,24,28.3,NaN,-1.334305,36.732963,-1.229613,36.764195,Rider_Id_958,3196
21183,Order_No_9070,User_Id_3521,Bike,3,Business,9,2,1:10:00 pm,9,2,...,1:34:13 pm,2,26.8,NaN,-1.270135,36.807217,-1.269691,36.815190,Rider_Id_88,877
21184,Order_No_22213,User_Id_237,Bike,3,Business,7,5,3:55:48 pm,7,5,...,5:43:17 pm,5,23.2,NaN,-1.255189,36.782203,-1.281242,36.819241,Rider_Id_523,701
21185,Order_No_25722,User_Id_59,Bike,3,Business,21,3,10:14:54 am,21,3,...,12:17:22 pm,7,22.2,NaN,-1.290894,36.822971,-1.255189,36.782203,Rider_Id_726,970
21186,Order_No_26544,User_Id_2145,Bike,3,Personal,12,3,12:13:10 pm,12,3,...,12:57:35 pm,6,19.3,NaN,-1.275285,36.802702,-1.292656,36.787318,Rider_Id_868,1235
21187,Order_No_12532,User_Id_478,Bike,3,Business,6,1,2:00:36 pm,6,1,...,3:02:58 pm,18,NaN,NaN,-1.217454,36.880191,-1.255189,36.782203,Rider_Id_691,1715
21188,Order_No_1396,User_Id_868,Bike,3,Business,4,2,11:04:42 am,4,2,...,11:27:02 am,3,18.9,NaN,-1.278385,36.816344,-1.265715,36.823815,Rider_Id_676,276
21189,Order_No_16829,User_Id_391,Bike,3,Business,12,3,10:19:41 am,12,3,...,11:23:29 am,5,19.5,NaN,-1.300921,36.828195,-1.286745,36.825902,Rider_Id_365,1368
21190,Order_No_16563,User_Id_3432,Bike,3,Business,25,1,5:13:44 pm,25,1,...,6:31:53 pm,13,27.5,NaN,-1.267259,36.800025,-1.338217,36.784572,Rider_Id_459,2364
21191,Order_No_16262,User_Id_1231,Bike,3,Business,1,4,2:09:37 pm,1,4,...,3:39:55 pm,13,NaN,NaN,-1.282142,36.816156,-1.215601,36.891686,Rider_Id_736,2807
21192,Order_No_11670,User_Id_1146,Bike,3,Business,23,2,12:41:17 pm,23,2,...,1:21:22 pm,7,NaN,NaN,-1.316711,36.830156,-1.308327,36.849476,Rider_Id_571,971
21193,Order_No_4988,User_Id_875,Bike,1,Personal,12,6,4:48:16 pm,12,6,...,5:56:53 pm,10,23.5,NaN,-1.286568,36.825335,-1.300106,36.758455,Rider_Id_103,1771
21194,Order_No_865,User_Id_1245,Bike,3,Business,15,1,5:02:09 pm,15,1,...,5:53:33 pm,16,NaN,NaN,-1.260234,36.799055,-1.319862,36.711032,Rider_Id_177,2298
21195,Order_No_9932,User_Id_3582,Bike,3,Business,2,6,1:08:34 pm,2,6,...,2:33:21 pm,17,29.0,NaN,-1.238406,36.871870,-1.276549,36.766981,Rider_Id_34,2325
21196,Order_No_8834,User_Id_2001,Bike,3,Personal,20,3,3:54:38 pm,20,3,...,4:20:17 pm,3,28.6,NaN,-1.258414,36.804800,-1.275285,36.802702,Rider_Id_953,9
21197,Order_No_22892,User_Id_1796,Bike,3,Business,13,6,10:13:34 am,13,6,...,10:46:17 am,7,26.0,NaN,-1.307143,36.825009,-1.331619,36.847976,Rider_Id_155,770
21198,Order_No_2831,User_Id_2956,Bike,3,Business,7,4,5:06:16 pm,7,4,...,6:40:05 pm,20,29.2,NaN,-1.286018,36.897534,-1.258414,36.804800,Rider_Id_697,2953
21199,Order_No_6174,User_Id_2524,Bike,1,Personal,4,3,9:31:39 am,4,3,...,10:08:15 am,13,15.0,NaN,-1.250030,36.874167,-1.279210,36.794872,Rider_Id_347,1380
21200,Order_No_9836,User_Id_718,Bike,3,Business,26,2,2:19:47 pm,26,2,...,3:17:23 pm,12,30.9,NaN,-1.255189,36.782203,-1.320157,36.830887,Rider_Id_177,2128